name = "Neo Forge"
author = "Markflynnman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63f440adfef32c38b1c469bf8254a655de27b1b338d107f9b5843c4f2ffeeefc"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
